export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const UPDATE_SHELTER_PROFILE_SUCCESS = "UPDATE_SHELTER_PROFILE_SUCCESS"
export const UPDATE_SHELTER_PROFILE_FAILURE = "UPDATE_SHELTER_PROFILE_FAILURE"
export const GET_SHELTER_INFO_SUCCESS = "GET_SHELTER_INFO_SUCCESS"
export const GET_SHELTER_INFO_FAILURE = "GET_SHELTER_INFO_FAILURE"
export const GET_ALL_SHELTERS_SUCCESS = 'GET_ALL_SHELTERS_SUCCESS';
export const GET_ALL_SHELTERS_FAILURE = 'GET_ALL_SHELTERS_FAILURE';

export const  UPDATE_VOLUNTEER_PROFILE_FAILURE = "UPDATE_VOLUNTEER_PROFILE_FAILURE"
export const UPDATE_VOLUNTEER_PROFILE_SUCCESS = "UPDATE_VOLUNTEER_PROFILE_SUCCESS"
export const GET_VOLUNTEER_INFO_FAILURE = "GET_VOLUNTEER_INFO_FAILURE"
export const GET_VOLUNTEER_INFO_SUCCESS = "GET_VOLUNTEER_INFO_SUCCESS"
